### PR TITLE
Fix/fetch only current employees

### LINKED ISSUE #68: Ikke hente ut ansatte som har sluttet + sortere etter navn
I api/employees burde vi legge til at vi ikke ønsker å hente ut ansatte som har sluttet. Dvs. at terminationDate ikke kan være før dagens dato. 
Denne burde også sorteres etter navn.

### PR DESCRIPTION
**Pull request by maxschau**
Closes #68 

- Added a check so that employees not working at Blank anymore is not displayed in EmployeeSelector
- Sorted by firstName, lastName

### CODE REVIEW

File: src/components/TextMarkDownWithLink.tsx [hunk 1]
```diff
@@ -10,19 +9,15 @@ export type TextMarkDownWithLinkProps = TypographyProps & {
...
-      )}
+      <Linkify
+        componentDecorator={(decoratedHref, decoratedText, key) => (
+          <a href={decoratedHref} key={key} rel='noreferrer' target='_blank'>
+            {decoratedText}
+          </a>
+        )}
+      >
+        <ReactMarkdown>{text}</ReactMarkdown>
+      </Linkify>
```
Comment (Zenjjim) [inline src/components/TextMarkDownWithLink.tsx:20]: La dette heller stå som det er også legg en {text && <TextMarkDownWithLink der denne brukes

**Review by Zenjjim — CHANGES_REQUESTED** [review]
